name: Release

on: 
  push:
    tags:
       - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.6
      with:
        type: "zip"
        path: "addons"
        filename: "${{github.event.repository.name}}-${{github.ref_name}}.zip"
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: "${{github.event.repository.name}}-${{github.ref_name}}.zip"
